### ISSUE TITLE
Missing holiday

### ISSUE THREAD

**Issue by rucksman** [rdmtc/node-red-contrib-german-holidays#19]
Is this node still under development?

If so, there is an error in the predefined holidays for "Berlin". Since some years now the "Internationaler Frauentag" is a holiday in Berlin.

On top of that it would be great to have a possibilty to enter a time period (instead of only single days) to use this node also for vacation flows.

If development of this node has been abandoned: is there an alternative to this node? Thank you!

**Comment by Hypnos3** [comment]
Yes, this node is still being developed. However, this is done with very low priority and therefore there are seldom releases.

**Comment by rucksman** [comment]
Added a PR for this issue.
