### ISSUE TITLE
Wrong Object Values

### ISSUE THREAD

**Issue by mivodu** [rdmtc/node-red-contrib-german-holidays#2]
It seems that the payload contains wrong values:
Today (30.05.2019 Christi Himmelfahrt) the following values are wrong (according to my understanding):
payload-> today -> month: 4 (shouldn't it be 5?)
payload-> today -> holiday -> dayOfWeek: 3 (shouldn't it be 4?)
payload-> today -> holiday -> day: 29 (should be 30)
payload-> today -> holiday -> month: 4 (should be 5)

I think the month is throughout the whole object filled with the wrong value (or at least it's not consistent, days of the month is starting with 1 while months are starting with 0 (for January).

**Comment by Hypnos3** [comment]
payload-> today -> month (shouldn't it be 5?)
this is the output of javascript [getMonth](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)
`The getMonth() method returns the month in the specified date according to local time, as a zero-based value (where zero indicates the first month of the year).`

In the next version there is the property `naturalMonth` which is the month starting 1 January.

But you are right, I noticed that not uniform UTC format is used. This has actually resulted in wrong expenses for the holidays.

I'm working to solve this.

**Comment by Hypnos3** [comment]
hopefully fixed with version 0.0.5

**Comment by mivodu** [comment]
Sorry for the late response, issue fixed and working as expected
