### ISSUE TITLE
Falscher Wert: "Tag der Arbeit"

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-german-holidays#3]
In der Version 0.1.1 ist der "Tag der Arbeit" falsch. Sieht nach einem Datumsdreher aus.

Ist: "Tag der Arbeit" = 05.01.19
Soll: "Tag der Arbeit" = 01.05.19

Gruß Thomas

**Comment by Hypnos3** [comment]
Danke!!
fixed mit 0.1.3
