### ISSUE TITLE
Fronleichnam fehlt =)

### ISSUE THREAD

**Issue by Dud3z** [rdmtc/node-red-contrib-german-holidays#4]
Da ich meine Rolladensteuerung an das Modul gekoppelt habe wurde ich heute morgen etwas unsanft geweckt ;-)

Kann Fronleichnam bei den entsprechenden Bundeslängern hinzugefügt werden?

**Comment by Hypnos3** [comment]
Hallo,

Oh, sorry.

Es gab schon Fronleichnam, fehlte nur in Bayern:
![image](https://user-images.githubusercontent.com/12692680/59832721-dad59380-9344-11e9-8066-201508ef01cf.png)

Ist mit Version 0.1.87 gefixed! - sollte in ca 1-2 Stunden verfügbar sein.

Gruß
