### ISSUE TITLE
Feiertag heute NAME ???

### ISSUE THREAD

**Issue by sblogoshs21** [rdmtc/node-red-contrib-german-holidays#5]
Weil gerade einer ist Frage ich mich warum bei so vielen Möglichkeiten es kein global day-info.holliday.name gibt.!? 
Für mich wäre erst damit die Sache komplett, den Namen des heutigen Feiertags abzurufen wird doch möglich sein.

Schöne Feiertage
Gruß Stefan

**Comment by Hypnos3** [comment]
Je nachdem welchen Input man gibt, liefert die Node doch `msg.payload.today.name`, was an einem Feiertag der Name des Feiertage ist.

**Comment by sblogoshs21** [comment]
Oh, dann habe ich das wohl übersehen. 
Vielen Dank!

Gruß Stefan
